# Generated by Django 3.0.5 on 2020-06-28 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gn_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gn_manager.Entry')),
            ],
        ),
    ]
