# Generated by Django 3.0.5 on 2020-07-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gn_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='initiallyScanned',
            field=models.BooleanField(default=False, verbose_name='Initially scanned?'),
        ),
    ]
