# Generated by Django 3.0.5 on 2020-07-23 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gn_manager', '0002_entry_initiallyscanned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Maximum Price'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Minimum Price'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='query',
            field=models.CharField(help_text='This is what will be searched. Be as specific as possible. Max: 250 characters.', max_length=250),
        ),
    ]
