# Generated by Django 3.0.5 on 2020-08-26 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gn_manager', '0003_auto_20200723_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.AlterField(
            model_name='entry',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Maximum Price ($)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Minimum Price ($)'),
        ),
    ]
